sudo: required
services:
  - docker

before_install:
  - docker build -t hudsondye/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hudsondye/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-833338994805"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
